In [47]:
import pandas as pd
import numpy as np

In [53]:
np.random.seed(5)
data_x1 = np.linspace(-10.0, 10.0, 20)[:, np.newaxis]
data_x1.shape

(20, 1)

In [50]:
new_data_x1 = np.hstack((np.ones_like(data_x1),data_x1))

In [55]:
order = np.random.permutation(20)
order

array([ 2,  5, 17, 19, 12,  1, 11, 10, 13, 18,  7,  4,  8,  9,  0, 16,  6,
       15, 14,  3])

In [58]:
new_data_x1[order[:3]]

array([[ 1.        , -7.89473684],
       [ 1.        , -4.73684211],
       [ 1.        ,  7.89473684]])

In [59]:
new_data_x1[order[3:]]

array([[  1.        ,  10.        ],
       [  1.        ,   2.63157895],
       [  1.        ,  -8.94736842],
       [  1.        ,   1.57894737],
       [  1.        ,   0.52631579],
       [  1.        ,   3.68421053],
       [  1.        ,   8.94736842],
       [  1.        ,  -2.63157895],
       [  1.        ,  -5.78947368],
       [  1.        ,  -1.57894737],
       [  1.        ,  -0.52631579],
       [  1.        , -10.        ],
       [  1.        ,   6.84210526],
       [  1.        ,  -3.68421053],
       [  1.        ,   5.78947368],
       [  1.        ,   4.73684211],
       [  1.        ,  -6.84210526]])