In [62]:
import numpy as np

In [120]:
# Write a Python program to print the NumPy
# version in your system.
print(np.version.full_version)
print(np.__version__)

1.19.2
1.19.2


In [7]:
# Write a Python program to reverse an array
# (first element becomes last)
arr = np.array([1,2,3,4,5,6])
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [124]:
# Write a Python program to convert a list and
# tuple into arrays.
lst = [[1,2,3],[4,5,6]]
tup = ((7,8,9),(10,11,12))
arr1 = np.asarray(lst)
arr2 = np.asarray(tup)
print(arr1,'\n')
print(arr2)

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]]


In [11]:
# Write a Python program to find common values
# between two arrays.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,1])
np.intersect1d(arr1,arr2)

array([1, 4, 5])

In [129]:
# Write a Python program compare two arrays
# using numpy.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,5])
print(np.equal(arr1,arr2),'\n')
print(np.greater(arr1,arr2),'\n')
print(np.less_equal(arr1,arr2),'\n')

[False False False False  True] 

[False False False False False] 

[ True  True  True  True  True] 



In [17]:
# Write a Python program to change the
# dimension of an array.
arr1 = np.array([1,2,3,4,5,6])
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
# Write a Python program (using numpy) to sum
# of all the multiples of 3 or 5 below 100.

arr = np.arange(1,100)
np.sum(arr[(arr%3 ==0)|(arr%5 == 0)])

2318

In [131]:
# Write a Python program to convert a NumPy
# array into Python list structure
arr1 = np.array([[1,2,3],[4,5,6]])
arr1.tolist()


[[1, 2, 3], [4, 5, 6]]

In [45]:
# Write a Python program to how to add an extra
# column to a numpy array.
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7],[9]])
np.append(arr1,arr2,axis=1)

array([[1, 2, 3, 7],
       [4, 5, 6, 9]])

In [50]:
# Write a Python program to check whether the
# numpy array is empty or not.
arr1 = np.array([[],[]])
np.size(arr1)

0

In [59]:
# Write a Python program to normalize a 3x3
# random matrix.
arr1 = np.array(np.random.randint(1,100,9)).reshape(3,3)
#arr1 = np.random.random((3,3))
arr_max, arr_min = arr1.max(), arr1.min()
(arr1-arr_min)/(arr_max-arr_min)

array([[0.5       , 0.41666667, 0.26666667],
       [0.05      , 0.38333333, 0.        ],
       [1.        , 0.9       , 0.28333333]])

In [99]:
# How to ignore all numpy warnings (not
# recommended)

In [81]:
# How to swap two rows of an array
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1,'\n')
arr1[[2,0]]= arr1[[0,2]]
print(arr1,'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[7 8 9]
 [4 5 6]
 [1 2 3]] 



In [98]:
# How to swap two columns of an array
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1,'\n')
arr1[:,[0,2]] = arr1[:,[2,0]]
print(arr1,'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[3 2 1]
 [6 5 4]
 [9 8 7]] 



In [90]:
# Compute bootstrapped 95% confidence
# intervals for the mean of a 1D array X (i.e.,
# resample the elements of an array with
# replacement N times, compute the mean of
# each sample, and then compute percentiles
# over the means).

X = np.random.randint(0,50,10) # random 1D array of size 10
N =  5 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[28.   38.66]


In [97]:
print(X.shape)
print(idx.shape)
print(means.shape)
print(X[idx].shape)

(10,)
(5, 10)
(5,)
(5, 10)


In [98]:
print(X,'\n')
print(idx,'\n')
print(X[idx],'\n')
print(means,'\n')


[24 44 43 41  4 48 42 40 35  5] 

[[6 6 4 6 2 6 0 7 6 9]
 [8 8 0 9 5 3 4 6 3 3]
 [8 7 6 0 1 1 8 5 7 7]
 [6 1 8 9 4 6 7 8 5 2]
 [4 0 2 1 3 0 4 4 7 5]] 

[[42 42  4 42 43 42 24 40 42  5]
 [35 35 24  5 48 41  4 42 41 41]
 [35 40 42 24 44 44 35 48 40 40]
 [42 44 35  5  4 42 40 35 48 43]
 [ 4 24 43 44 41 24  4  4 40 48]] 

[32.6 31.6 39.2 33.8 27.6] 



In [36]:
idx

array([[13, 53, 21, ..., 54, 12, 24],
       [71,  1, 31, ..., 24, 50, 18],
       [85, 80, 45, ..., 85, 40, 31],
       ...,
       [57, 70, 18, ..., 99, 29, 52],
       [31, 33, 55, ..., 97, 82, 59],
       [65, 46, 12, ..., 83, 98, 72]])

In [60]:
X = np.array([0,1,2,3,4,5,6,7,8,9,10])
idx = np.array([1,2,3,4]).reshape(2,2)

In [61]:
X[idx]

array([[1, 2],
       [3, 4]])

In [44]:
X[[1, 2],[3, 4]]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [41]:
idx

array([[1, 2],
       [3, 4]])

In [53]:
b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(1)

In [54]:
sumrow

array([10,  9, 20])

In [55]:
array1 = np.arange(18).reshape(3,2,3)

In [63]:
array1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [59]:
array1[0,1,2]

5

In [73]:
a = np.array([[5, 5,10,6],[4, 5,2,3],[16,27,2, 4]])

In [74]:
a

array([[ 5,  5, 10,  6],
       [ 4,  5,  2,  3],
       [16, 27,  2,  4]])

In [79]:
a[2]

array([16, 27,  2,  4])

In [103]:
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [104]:
rows = np.array([[0, 0],
          [2, 2]])

In [105]:
cols = np.array([[0, 1],
                 [2, 2]])

In [106]:
x[rows, cols]

array([[0, 1],
       [8, 8]])

In [108]:
x = np.random.randint(0,2,6)
y = np.random.randint(0,2,6)


In [109]:
x

array([1, 0, 1, 1, 0, 1])

In [110]:
y

array([0, 0, 0, 0, 1, 1])

In [111]:
np.allclose(x,y)

False

In [119]:
np.datetime64('today','D')

numpy.datetime64('2022-01-21')

In [139]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1,'\n')
arr1[[1]]


[[1 2 3]
 [4 5 6]
 [7 8 9]] 



array([[4, 5, 6]])

In [140]:
arr1[:,1]

array([2, 5, 8])