In [6]:
# 56. Write a Python program that takes any number of iterable objects or 
# objects with a length property and returns the longest one

def return_longest(*args):
    return max(args, key = len)

return_longest([2,3,4,56,6],'compliment',(2,3,1,3,5,6))


'compliment'

In [9]:
import pandas as pd
import numpy as np
help(np.all)

Help on function all in module numpy:

all(a, axis=None, out=None, keepdims=<no value>)
    Test whether all array elements along a given axis evaluate to True.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical AND reduction is performed.
        The default (``axis=None``) is to perform a logical AND over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.
        It must have the same shape as the expected output and its
        type is preserved (e.g., if ``dtype(out)`` is flo

In [11]:
help(np.allclose)

Help on function allclose in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    NaNs are treated as equal if they are in the same place and if
    ``equal_nan=True``.  Infs are treated as equal if they are in the same
    place and of the same sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output a

In [12]:
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes


In [18]:
np.identity(3)*7

array([[7., 0., 0.],
       [0., 7., 0.],
       [0., 0., 7.]])

In [19]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution

In [22]:
np.ones(6).reshape(3,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
x = np.arange(10)
x[(x>5) & (x<9)]*= -1
x

array([ 0,  1,  2,  3,  4,  5, -6, -7, -8,  9])

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [48]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])

In [49]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [50]:
arr[1:2,1:-1]

array([[ 9, 10, 11, 12, 13]])

In [51]:
x = (np.ones(100)*7).reshape(10,10)
x[1:9,1:-1] = 0
x

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [60]:
x = np.diag([1,2,3,4])
x

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

TypeError: 'builtin_function_or_method' object is not iterable

In [69]:
x = np.ones(16).reshape(4,4)

In [70]:
x.diagonal()

array([1., 1., 1., 1.])

In [72]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
result = np.empty_like(m) 

In [73]:
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
x = np.empty_like(m)
counter = 0
for each in m:
    m[counter,::] = each + v
    counter +=1
m

array([[ 2,  3,  3],
       [ 5,  6,  6],
       [ 8,  9,  9],
       [11, 12, 12]])

In [90]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [94]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
m[0,::]

array([1, 2, 3])