In [11]:
import numpy as np

ar = np.array([[1,2],[2,3]], ndmin = 5)

In [12]:
ar.shape

(1, 1, 1, 2, 2)

In [13]:
ar.ndim

5

In [27]:
x = np.array([[[[1],[2], [3]]]])
print(x.ndim, x.shape)
print(x)
z = x.reshape(3,1,1,1,1)
print(z)
print(z.ndim)

4 (1, 1, 3, 1)
[[[[1]
   [2]
   [3]]]]
[[[[[1]]]]



 [[[[2]]]]



 [[[[3]]]]]
5


In [29]:
x = np.array([1,2,3])
print(x.ndim, x.shape)

1 (3,)


In [35]:
x.reshape(3,)

array([1, 2, 3])

In [48]:
a = np.array([[[1,2,3,5],[4,5,6,2]],[[7,8,9,6],[10,11,12,1]]])

In [49]:
a.shape

(2, 2, 4)

In [51]:
a.ndim

3

In [42]:
for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [50]:
for i in a.reshape(16,):
    print(i)

1
2
3
5
4
5
6
2
7
8
9
6
10
11
12
1


In [52]:
a.shape

(2, 2, 4)

In [56]:
a.shape[0]

2

In [57]:
np.prod(np.array(a.shape))

16

In [63]:
for i in a.reshape(np.prod(np.array(a.shape)),):
    print(i)

1
2
3
5
4
5
6
2
7
8
9
6
10
11
12
1


In [59]:
a

array([[[ 1,  2,  3,  5],
        [ 4,  5,  6,  2]],

       [[ 7,  8,  9,  6],
        [10, 11, 12,  1]]])

In [60]:
a.reshape(-1)

array([ 1,  2,  3,  5,  4,  5,  6,  2,  7,  8,  9,  6, 10, 11, 12,  1])

In [65]:
a.reshape(-1)

array([ 1,  2,  3,  5,  4,  5,  6,  2,  7,  8,  9,  6, 10, 11, 12,  1])

In [67]:
a = np.array([[1,2],[3,4],[8,2]])

In [76]:
np.ptp(a,0)

array([7, 2])

In [71]:
a.shape

(3, 2)

In [77]:
np.sum(a,0)

array([12,  8])

In [79]:
import pandas as pd
import numpy as np

In [89]:

df = pd.read_excel(r"C:\Users\j1013189\Downloads\CP13_Evidence_BY_DvSUM.xlsx",sheet_name=1,header=0)

In [94]:
df.head()

Data Object    Scope Inbound From  \
0           Weekly Sales Transaction History (Count)      WES     Algonomy   
1  Weekly Sales Transaction History (Count) - Cou...  WES-ARE     Algonomy   
2  Weekly Sales Transaction History (Count) - LOC...    30127     Algonomy   
3  Weekly Sales Transaction History (Count) - LOC...    30133     Algonomy   
4  Weekly Sales Transaction History (Count) - LOC...    30823     Algonomy   

  Outbound To Metric Type  Metric Inbound  Metric Outbound  Metric Delta  \
0          BY       Count        102537.0         100026.0        2511.0   
1          BY       Count         46988.0          46725.0         263.0   
2          BY       Count          8569.0           8544.0          25.0   
3          BY       Count          4089.0           4068.0          21.0   
4          BY       Count           797.0            797.0           0.0   

   Delta Percentage  Data Migration ID Data Migration Date  BY Omhand  \
0          0.024489                NaN     22 October 2021        NaN   
1          0.005597                NaN     22 October 2021        NaN   
2          0.002917                NaN     22 October 2021        NaN   
3          0.005136                NaN     22 October 2021        NaN   
4          0.000000                NaN     22 October 2021        NaN   

                                            Comments  
0  Item Location in Algonomy table is not active ...  
1  Item Location in Algonomy table is not active ...  
2  Item Location in Algonomy table is not active ...  
3  Item Location in Algonomy table is not active ...  
4                                                NaN

In [110]:
df[(df["Scope"] == "WES") & (df["Delta Percentage"] > 0)]

Data Object Scope Inbound From Outbound To  \
0    Weekly Sales Transaction History (Count)   WES     Algonomy          BY   
35    Weekly Sales Transaction History (Unit)   WES     Algonomy          BY   
140              Weekly Stock On Hand History   WES     Algonomy          BY   

           Metric Type  Metric Inbound  Metric Outbound  Metric Delta  \
0                Count        102537.0         100026.0        2511.0   
35   Total Sales Units        100312.0         100237.0          75.0   
140              Count        636101.0         392300.0      243801.0   

     Delta Percentage  Data Migration ID Data Migration Date  BY Omhand  \
0            0.024489                NaN     22 October 2021        NaN   
35           0.000748                NaN     22 October 2021        NaN   
140          0.383274                NaN     22 October 2021        NaN   

                                              Comments  
0    Item Location in Algonomy table is not active ...  
35   Item Location in Algonomy table is not active ...  
140  Item Location is not active in Dvsum RMS or do...