In [17]:
import numpy as np
# NumPy array with elements from 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 
# Index values can be negative.
arr = x[np.array([1, 3, -3])]
print("\n Elements are : \n",arr)


 Elements are : 
 [2 4 7]


In [15]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:

# Python program for basic slicing.
import numpy as np
 
# Arrange elements from 0 to 19
a = np.arange(20)
print("\n Array is:\n ",a)
 
# a[start:stop:step]
print("\n a[-8:17:1] = ",a[-8:17:1])
 
# The : operator means all elements till the end.
print("\n a[10::2] = ",a[10::])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1] =  [12 13 14 15 16]

 a[10::2] =  [10 11 12 13 14 15 16 17 18 19]


In [35]:
b = np.array([[[1, 2, 3],[4, 5, 6]],
            [[7, 8, 9],[10, 11, 12]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
b[1,:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [42]:
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]


In [55]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
# You may wish to select those elements whose
# sum of row is a multiple of 10.
import numpy as np
 
array = np.array(np.linspace(0,5,10))

In [62]:
array.reshape(10,1,1)

array([[[0.        ]],

       [[0.55555556]],

       [[1.11111111]],

       [[1.66666667]],

       [[2.22222222]],

       [[2.77777778]],

       [[3.33333333]],

       [[3.88888889]],

       [[4.44444444]],

       [[5.        ]]])

In [65]:
arr = np.full((2,2,2),4)
arr

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [68]:
np.ndim(arr)

3

In [70]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
np.shape(arr)

(4, 4)

In [74]:
arr[:2,:1:2]

array([[-1.],
       [ 4.]])

In [77]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [78]:
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
temp

array([2. , 4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. , 2. ])

In [79]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [88]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [89]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [90]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [92]:
#Everything from (including) the second item to (not including) the fifth item.
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[1:4]


array([15, 20, 25])

In [5]:
import time
def decorForFactorial(func):
    print("Check 0")
    def getStartTime(args):

        print("Check 1")
        returnvalue = getFactorial(args)
        print("Check 2")
        return returnvalue
    return getStartTime

@decorForFactorial
def getFactorial(n):
    print("Inside Get Factorial")
    return n*n
    

Check 0


In [ ]:
x = getFactorial(2)
x

Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1
Check 1


In [1]:
# Another example
def my_decorator(func):

    def get_types(*args):
        print("before Execution")
        
        for each in args:
            print(type(each))

        returned_value = func(*args)
        print("after Execution")
        return(returned_value)
    return get_types

@my_decorator
def my_add_functon(a,b):
    print("Inside the function")
    return(a+b)

In [2]:
ans = my_add_functon(2,3)
ans

before Execution
<class 'int'>
<class 'int'>
Inside the function
after Execution


5